### ISSUE TITLE
UAVid datasets

### ISSUE THREAD

**Issue by VAriana** [WangLibo1995/GeoSeg#1]
Hi，I’m reproducing the results of your paper,but I have some problems with the dataset.
Can I use the UAVid datasets without changing any codes?
should I use the UAVid toolkit to process the data?
waiting for your comments!

**Comment by WangLibo1995** [comment]
Thank you for your interest! Which paper do you want to reproducing?

**Comment by VAriana** [comment]
Thanks for your reply.I want to reproduce the Unet-like Transformer.
I have read the paper that includes the result of using UAVid dataset to train the model.This is exactly what I want to do.

**Comment by WangLibo1995** [comment]
> Thanks for your reply.I want to reproduce the Unet-like Transformer. I have read the paper that includes the result of using UAVid dataset to train the model.This is exactly what I want to do.

The code of UNetFormer will be open if it is published. For further scholar discussion, I recommend to use institution email.

**Comment by VAriana** [comment]
thanks for you advice! I still have one problem that whether the GeoSeg could be used on UAVid dataset directly.
Because the instruction only introduced how to process the segmentation task on LoveDA.
Should I process the dataset with UAVtoolkit and revise the code?

**Comment by WangLibo1995** [comment]
> thanks for you advice! I still have one problem that whether the GeoSeg could be used on UAVid dataset directly. Because the instruction only introduced how to process the segmentation task on LoveDA. Should I process the dataset with UAVtoolkit and revise the code?

The script of processing UAVid also will be open if the paper is published. My email is wanglibo@whu.edu.cn. Thank you for your attention again.
