### ISSUE TITLE
对于数据存放存在疑问

### ISSUE THREAD

**Issue by hpoqe** [WangLibo1995/GeoSeg#10]
只需要把RGB和labels_all文件按照文中划分就可以放入模型了吗？但是我看到在还有一个rain文件和一个eroded文件,如果说eorded文件如果是带有边界的，那么在另外一个问题说是放在测试集，但是文件夹名称却是以train_mask_eroded命名，此外对于边界文件是原文件中的labels_for_participants文件中的吗？还是有关其他源文件的其它文件，请指教，谢谢！

**Comment by WangLibo1995** [comment]
可以参考这个链接 
https://pan.baidu.com/s/1NoRVJgLvJjedTnwhqJ8Gbw 
8qjo

**Comment by WangLibo1995** [comment]
train_masks_eroded没有用到，eroded label文件名有标注



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月31日(周日) 中午11:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [WangLibo1995/GeoSeg] 对于数据存放存在疑问 (Issue #10)




 
只需要把RGB和labels_all文件按照文中划分就可以放入模型了吗？但是我看到在还有一个rain文件和一个eroded文件,如果说eorded文件如果是带有边界的，那么在另外一个问题说是放在测试集，但是文件夹名称却是以train_mask_eroded命名，此外对于边界文件是原文件中的labels_for_participants文件中的吗？还是有关其他源文件的其它文件，请指教，谢谢！
