### ISSUE TITLE
The pretraind models

### ISSUE THREAD

**Issue by rose-jinyang** [WangLibo1995/GeoSeg#12]
Hello
How are you?
Thanks for contributing to this project.
Could u explain about the pre-weights that u shared in this repo in detail?

![image](https://user-images.githubusercontent.com/47862419/184782557-735ac9f2-9f8c-4c12-8196-8bda7e8869d0.png)

**Comment by WangLibo1995** [comment]
Pre-weights are downloaded from their official repo. I processed some "key" in the state_dict to match with my models.

**Comment by rose-jinyang** [comment]
So these pre-weights were trained on such dataset like ImageNet-21K, right?
If yes, these were trained with UNetFormer architectture, right?

**Comment by WangLibo1995** [comment]
Pre-weights details on https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation https://github.com/rwightman/pytorch-image-models

**Comment by rose-jinyang** [comment]
But I can NOT see where these pre-weights are being used directly in your repo.

**Comment by rose-jinyang** [comment]
Oh, just found, these pre-weights are for training with DC-Swin network, right?

![image](https://user-images.githubusercontent.com/47862419/184790773-efa5e346-bdb7-4669-a398-1399ec386741.png)

**Comment by WangLibo1995** [comment]
Yes

> Oh, just found, these pre-weights are for training with DC-Swin network, right?
> 
> ![image](https://user-images.githubusercontent.com/47862419/184790773-efa5e346-bdb7-4669-a398-1399ec386741.png)

Yes
