### ISSUE TITLE
About Vaihingen and Potsdam datasets

### ISSUE THREAD

**Issue by rose-jinyang** [WangLibo1995/GeoSeg#13]
Hello
How are you?
I have a quick question.
I saw that u trained models on each dataset respectively and used different crop sizes (Vaihingen: 512, Potsdam: 768).
I downloaded the dataset processed by you from here.

![image](https://user-images.githubusercontent.com/47862419/184802862-41832c90-002e-4982-b1ed-fd3bd0a3c927.png)

The tree and grass are red color in train images of Vaihingen dataset but not in train images of Potsdam.

![image](https://user-images.githubusercontent.com/47862419/184802140-286e134c-73c7-4077-8279-27f835a6d6a9.png)

![image](https://user-images.githubusercontent.com/47862419/184802236-3711c571-3ece-4e22-abfc-558f28ebecc5.png)

Could u explain about this?
Can we train a model on both Vaihingen and Potsdam datasets?

**Comment by WangLibo1995** [comment]
Something difference between Vaihingen and Potsdam, such as the bands, IR, R, G for Vaihingen, R,G,B for Postdam. This is the reason for different color. Based on this, I do not think it is a good choice to train a model on both of the two datasets.

**Comment by rose-jinyang** [comment]
Thanks for your quick reply.
