### ISSUE TITLE
关于测试集的一个问题

### ISSUE THREAD

**Issue by WBS-123** [WangLibo1995/GeoSeg#16]
感谢您的工作！有一个问题想咨询您：
由于测试的时候通常是将一整幅图像裁剪成patch分别预测，最后拼接在一起，这通常会导致明显的分块效应，但是我看到您文章里报告的结果没有明显的分块效应，请问是采用了什么处理手段吗？

**Comment by mxw1** [comment]
我也很好奇。看代码，作者也是裁剪为patch分别预测后拼接在一起的，但是为什么没有明显的分块效应，是还采用了其他处理手段吗

**Comment by WangLibo1995** [comment]
精度上去了，分块效应自然缓解很多。预测的时候用大尺寸的输入也是较为有效的手段
