### ISSUE TITLE
Key error:'state_dict'

### ISSUE THREAD

**Issue by VAriana** [WangLibo1995/GeoSeg#2]
Hi!
What can I do to solve this error?
<img width="605" alt="1652434235(1)" src="https://user-images.githubusercontent.com/102912455/168255216-9917d3e9-9e07-4273-9959-292f7187ac27.png">

**Comment by WangLibo1995** [comment]
> Hi! What can I do to solve this error? <img alt="1652434235(1)" width="605" src="https://user-images.githubusercontent.com/102912455/168255216-9917d3e9-9e07-4273-9959-292f7187ac27.png">

Maybe try ’model_state_dict’？You need to make keys of pretrain weight matched with the DCSwin’ keys

**Comment by VAriana** [comment]
I have solved the problem by using the key 'models'
<img width="478" alt="1652443592(1)" src="https://user-images.githubusercontent.com/102912455/168279764-1d3ea689-b3d0-4aa8-809d-6ded418e212d.png">
