### ISSUE TITLE
关于测试集和训练集的标签

### ISSUE THREAD

**Issue by icey-zhang** [WangLibo1995/GeoSeg#21]
您好，请问一下为什么训练数据的标签是没有boundary，但是测试数据却是有boundary
照理说有没有boundary都不会影响测试结果，但我的测试结果这两种方式的测试精度差了许多
没有boundary的 F1:0.8584966021073827, mIOU:0.7559513978362932, OA:0.8748274848804155
有boundary的 F1:0.8933666820418791, mIOU:0.8098527822309285, OA:0.9018810909262144
请问为什么测试的时候选有boundary作为标签？
为什么这两种方式的差距这么大呀？

**Comment by WangLibo1995** [comment]
> 您好，请问一下为什么训练数据的标签是没有boundary，但是测试数据却是有boundary 照理说有没有boundary都不会影响测试结果，但我的测试结果这两种方式的测试精度差了许多 没有boundary的 F1:0.8584966021073827, mIOU:0.7559513978362932, OA:0.8748274848804155 有boundary的 F1:0.8933666820418791, mIOU:0.8098527822309285, OA:0.9018810909262144 请问为什么测试的时候选有boundary作为标签？ 为什么这两种方式的差距这么大呀？

这个是参考之前论文的做法，也是为了方便进行比较
