### ISSUE TITLE
关于跑分偏低

### ISSUE THREAD

**Issue by Timiain** [WangLibo1995/GeoSeg#22]
（求救...）
尝试复现的过程中发现跑不到论文的结果
![piur](https://user-images.githubusercontent.com/68993661/195527377-88e59005-ef44-4013-a2d6-03ea492edb20.png)

RR: random rotate 
RF: random flip 
N: normalize

80k-是mmseg的默认的hrnet - 80k iter
105e-是这个github的105 epoch

100e-1024x1024-RF:RR:N-UNetFormer-crop512 应该是论文的training setting
100e-1024x1024-RR:N-UNetFormer-crop1024 是这个github的默认setting

![2022-10-13 15-19-06屏幕截图](https://user-images.githubusercontent.com/68993661/195528543-85e92eef-601d-4368-a05d-aaad92a2cc68.png)
复现结果分别是 81.9 和 80.5 
但论文的设置为82.7

同样的情况发生在了potsdam
![2022-10-13 15-20-26屏幕截图](https://user-images.githubusercontent.com/68993661/195528835-f45fd517-bc74-4511-a025-61f7ff9225f5.png)
![2022-10-13 15-20-54屏幕截图](https://user-images.githubusercontent.com/68993661/195528913-d26376cd-e56f-48c2-855f-aa7e82b4ce24.png)

**Comment by WangLibo1995** [comment]
调调参，我的参数未必适合你的机器。这我师弟复现的vaihingen结果 
链接：https://pan.baidu.com/s/14sv4qKqpfilNgFCR1h1M4g 
提取码：1234
![KROWS13FHF3TVIS~D7$Q`7I](https://user-images.githubusercontent.com/38718224/195763857-0ae63826-4654-40e7-8ed7-b4137c2eb413.png)

测试时用一下TTA：
```
python GeoSeg/vaihingen_test.py -c GeoSeg/config/vaihingen/unetformer.py -o fig_results/vaihingen/unetformer-res18 --rgb -t 'd4'
```

**Comment by Timiain** [comment]
谢谢回答，test性能+tta其实是更低的，val的性能还好点，我先试试用你的预训练模型
