### ISSUE TITLE
关于masks划分

### ISSUE THREAD

**Issue by just1226** [WangLibo1995/GeoSeg#25]
你好！请问我运行vaihingen_patch_split.py后，为什么train/masks里的标签是全黑？
期待你的回复！

**Comment by oolongscu** [comment]
跑通了吗，老兄

**Comment by just1226** [comment]
没有，跑到一半报错。




Huangpeng
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WangLibo1995/GeoSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月28日(星期五) 中午1:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WangLibo1995/GeoSeg] 关于masks划分 (Issue #25)





 
跑通了吗，老兄

**Comment by oolongscu** [comment]
me too
