### ISSUE TITLE
关于训练结果的问题

### ISSUE THREAD

**Issue by ZhangIceNight** [WangLibo1995/GeoSeg#28]
你好，感谢分享代码
我们在复现论文DCSwin的结果的时候，遇到了一些问题，我们最高只有89左右，配置文件完全保持和代码库里一致，没有做任何修改。
请问是否有那里是我们需要改动的，或是有任何什么原因可能导致这个问题？
再次感谢，希望可以得到回复

**Comment by WangLibo1995** [comment]
> 你好，感谢分享代码 我们在复现论文DCSwin的结果的时候，遇到了一些问题，我们最高只有89左右，配置文件完全保持和代码库里一致，没有做任何修改。 请问是否有那里是我们需要改动的，或是有任何什么原因可能导致这个问题？ 再次感谢，希望可以得到回复

你好，感谢你的关注。
1.Github中的DCSwin config给了一个多尺度训练和测试的例子，测试时需要配合vaihingen_test.py并且使用“d4” 测试增强，请检查一下。测试结果最好能提供一下截图。
2.对于vaihinngen数据集，我们切块的时候（vaihingen_patch_split.py）已经做了随机翻转的数据增广，你也可以在config中不使用任何数据增强进行训练，然后测试时用“lr”测试增强。
3.硬件环境也很重要
