### ISSUE TITLE
The fn,fp and tp is wrong 

### ISSUE THREAD

**Issue by tinggh** [WangLibo1995/GeoSeg#5]
In function get_tp_fp_tn_fn of tools\metric.py, the computation of fn, fp and tn is wrong, to my point of view:
tp = np.diag(self.confusion_matrix)
fp = self.confusion_matrix.sum(axis=0) - tp
fn = self.confusion_matrix.sum(axis=1) - tp
tn =np.sum(self.confusion_matrix) - fp - fn + tp

**Comment by WangLibo1995** [comment]
> In function get_tp_fp_tn_fn of tools\metric.py, the computation of fn, fp and tn is wrong, to my point of view: tp = np.diag(self.confusion_matrix) fp = self.confusion_matrix.sum(axis=0) - tp fn = self.confusion_matrix.sum(axis=1) - tp tn =np.sum(self.confusion_matrix) - fp - fn + tp

Can you provide some reference to support your point? I test with your code, nothing change in F1, OA and ioU.

**Comment by tinggh** [comment]
Yes, all these indexes is symetric for fn and fp, so the result is not changed. This article is for your reference： https://0809zheng.github.io/2021/09/09/segmenteval.html

**Comment by WangLibo1995** [comment]
Thank you for your suggestion. I will update it.



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 6, 2022 17:00 PM
To: ***@***.***&gt;;
Cc: "Libo ***@***.******@***.***&gt;;
Subject: Re: [WangLibo1995/GeoSeg] The fn,fp and tp is wrong  (Issue #5)




 
Yes, all these indexes is symetric for fn and fp, so the result is not changed. This article is for your reference： https://0809zheng.github.io/2021/09/09/segmenteval.html
