### ISSUE TITLE
Uvaid

### ISSUE THREAD

**Issue by NicoleLiYueqi** [WangLibo1995/GeoSeg#6]
Hi, I'm wondering if you posted code for Uavid dataset?

**Comment by WangLibo1995** [comment]
> Hi, I'm wondering if you posted code for Uavid dataset?

Thank you for your attention. The code will be updated in the next version

**Comment by NicoleLiYueqi** [comment]
Thank you so much for your fast reply!

**Comment by WangLibo1995** [comment]
> Thank you so much for your fast reply!

UAVid and UNetformer are supported now.

**Comment by WangLibo1995** [comment]
UAVid and UNetformer are supported now.
