### ISSUE TITLE
Vaihingen Data Preprocessing 

### ISSUE THREAD

**Issue by NicoleYueqiLi** [WangLibo1995/GeoSeg#7]
Thank you so much for sharing your code in GitHub, they are extremely helpful!

I'm wondering if you could give me some instructions on how to do data preprocessing for Vaihingen Dataset? When I download the data from [isprs](https://seafile.projekt.uni-hannover.de/f/6a06a837b1f349cfa749/) website, the dataset does not split into training/Val/Testing. So, I wasn't able to use` vaihingen_patch_split.py`. I'm wondering if I should download it from somewhere else if so, do you mind sending me the link? Or, should I split the data by myself?

Thank you so much for any help or suggestion you may have!

**Comment by WangLibo1995** [comment]
Yes，you should split it yourself.



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 13, 2022 09:56 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [WangLibo1995/GeoSeg] Vaihingen Data Preprocessing  (Issue #7)




 
Thank you so much for sharing your code in GitHub, they are extremely helpful!
 
I'm wondering if you could give me some instructions on how to do data preprocessing for Vaihingen Dataset? When I download the data from isprs website, the dataset does not split into training/Val/Testing. So, I wasn't able to use vaihingen_patch_split.py. I'm wondering if I should download it from somewhere else if so, do you mind sending me the link? Or, should I split the data by myself?
 
Thank you so much for any help or suggestion you may have!
