### ISSUE TITLE
vaihingen files

### ISSUE THREAD

**Issue by scm-later** [WangLibo1995/GeoSeg#8]
您好，我c从官网下载的vaihingen数据集，其中包含了好几个文件夹，如下图所示，请问我应该按照怎样的组织方式将其放到该项目的vaihingen文件夹下呢,,可以详细说明吗，感谢！！
![1](https://user-images.githubusercontent.com/89558994/181787826-659e74dc-6181-4b68-ab24-89cd8bd1039e.PNG)
![2](https://user-images.githubusercontent.com/89558994/181787827-ed5b19e5-5494-43c6-ba35-5233459ea14d.png)

**Comment by WangLibo1995** [comment]
你好，感谢你的关注，需根据图片ID划分训练集和测试集（参考论文里的Dataset章节），注意vaihingen和potsdam的mask有两种，一种是eroded，一种是常规的，需要区分开来
