### ISSUE TITLE
类别

### ISSUE THREAD

**Issue by long123524** [WangLibo1995/GeoSeg#9]
您好，您在划分影像和标签的时候，产生了有7个类别（0-6，Vaihingen数据集）。这意味着训练的时候应该按照7个类别来训练吗？但看您的论文上只是展示的图是前六个类别，但精度评价却是只提到了前五个类别，测试文件也是按照6个类别来进行的。我有个疑惑，这到底应该是按照几个类别来进行训练和预测呢？

**Comment by WangLibo1995** [comment]
> 您好，您在划分影像和标签的时候，产生了有7个类别（0-6，Vaihingen数据集）。这意味着训练的时候应该按照7个类别来训练吗？但看您的论文上只是展示的图是前六个类别，但精度评价却是只提到了前五个类别，测试文件也是按照6个类别来进行的。我有个疑惑，这到底应该是按照几个类别来进行训练和预测呢？

您好，您可以注意下生成训练集和测试集时的masks路径。训练数据用的是常规masks，只有6类用于训练。测试数据用的是eroded masks有七个类，多了一个是Boundary类（应该被ignored）。参照之前的一些工作，文中公布精度的类别是五类，去掉了Clutter类，因为该类别样本量很少且不是人们所关心的地物。

**Comment by WangLibo1995** [comment]
> 您好，您在划分影像和标签的时候，产生了有7个类别（0-6，Vaihingen数据集）。这意味着训练的时候应该按照7个类别来训练吗？但看您的论文上只是展示的图是前六个类别，但精度评价却是只提到了前五个类别，测试文件也是按照6个类别来进行的。我有个疑惑，这到底应该是按照几个类别来进行训练和预测呢？

您好，您可以注意下生成训练集和测试集时的masks路径。训练数据用的是常规masks，只有6类用于训练。测试数据用的是eroded masks有七个类，多了一个是Boundary类（应该被ignored）。参照之前的一些工作，文中公布精度的类别是五类，去掉了Clutter类，因为该类别样本量很少且不是人们所关心的地物。

**Comment by long123524** [comment]
谢谢你的答复。我想问一下你有遇到过Clutter类别的F1指标为nan的情况吗，其他五类却都是正常的。

**Comment by WangLibo1995** [comment]
> 谢谢你的答复。我想问一下你有遇到过Clutter类别的F1指标为nan的情况吗，其他五类却都是正常的。

这个好像没有过，一半nan问题出在loss上。
